Update to local url
A local url was going through to production which was causing errors saying that the follows -
 TypeError: Failed to construct 'URL': Invalid URL